return {
  'folke/snacks.nvim',
  priority = 1000,
  lazy = false,
  init = function() end,
  opts = {
    animate = { enabled = false },
    bigfile = { enabled = true },
    buffdelete = { enabled = false },
    dashboard = { enabled = true },
    debug = { enabled = false },
    dim = { enabled = false },
    explorer = { enabled = true },
    git = { enabled = false },
    gitbrowse = { enabled = false },
    image = { enabled = false },
    indent = { enabled = true },
    input = { enabled = false },
    layout = { enabled = false },
    lazygit = { enabled = false },
    notifier = { enabled = false },
    notify = { enabled = false },
    picker = { enabled = false },
    profiler = { enabled = false },
    quickfile = { enabled = true },
    rename = { enabled = false },
    scope = { enabled = false },
    scratc = { enabled = false },
    hscroll = { enabled = false },
    statuscolumn = { enabled = false },
    terminal = { enabled = false },
    toggle = { enabled = false },
    util = { enabled = false },
    win = { enabled = false },
    words = { enabled = false },
    zen = { enabled = false },
  },
  keys = {
    {
      '<leader>e',
      function()
        Snacks.explorer.open()
      end,
      desc = 'Toggle explorer',
      mode = 'n',
    },
    {
      '<leader>t',
      function()
        Snacks.terminal.toggle(cmd)
      end,
      desc = 'Toggle terminal',
      mode = 'n',
    },
  },
}
